# config.yaml
experiment:
  name: "dummy_run"
  seed: 42
  save_dir: "checkpoints/"
  log_dir: "logs/"

model:
  name: "DummyModel"
  config:
    param:
      input_dim: 10
      output_dim: 2

dataset:
  name: "DummyDataset"
  train_path: "data/train.csv"
  val_path: "data/val.csv"
  val_split: 0.2


training:
  epochs: 5
  lr: 0.001
  optimizer: "Adam"
  weight_decay: 0.0
  scheduler: null
  batch_size: 16


loss:
  name: "DummyLoss"

optimizer:
  name: "Adam"
  params:
    lr: 0.001
    weight_decay: 0.0

scheduler:
  name: "StepLR"
  params:
    step_size: 10
    gamma: 0.1


logger:
  name: "train_logger1"
  log_file: "./logs/training1.log"
  log_level: "INFO"
  log_format: "[%(asctime)s] %(levelname)s - %(message)s"
